import { lazy, type ComponentType } from "react"
import type { LucideIcon } from "lucide-react"
import {
  Coffee,
  Layers,
  Play,
  Cpu,
  FileCode2,
  Variable,
  Calculator,
  Split,
  Repeat,
  Grid2x2,
  Type,
  SquareFunction,
  ArrowLeftRight,
  Box,
  Hammer,
  Lock,
  Pin,
  Network,
  Shapes,
  Frame,
  Plug,
  Equal,
  Puzzle,
  ToggleLeft,
  Receipt,
  PackageOpen,
  FolderTree,
  MemoryStick,
  Send,
  Recycle,
  Droplets,
  Boxes,
  ListOrdered,
  KeyRound,
  Hash,
  ArrowDownUp,
  Braces,
  Asterisk,
  TriangleAlert,
  ShieldAlert,
  LifeBuoy,
  HardDrive,
  Zap,
  Workflow,
  Waves,
  Filter,
  CircleHelp,
  Sparkles,
  CalendarClock,
  Activity,
  LockKeyhole,
  Gauge,
  Rabbit,
  PackageCheck,
  FlaskConical,
  ClipboardCheck,
  LibraryBig,
  CircleDot,
  Factory,
  Construction,
  Signpost,
  Radio,
  Component,
  Unplug,
  LayoutTemplate,
  Radar,
} from "lucide-react"

export type Section =
  | "foundations"
  | "syntax"
  | "oop"
  | "design"
  | "memory"
  | "collections"
  | "errors"
  | "modern"
  | "concurrency"
  | "tooling"
  | "patterns"

export const SECTIONS: Record<Section, string> = {
  foundations: "Java Foundations",
  syntax: "Syntax & Control Flow",
  oop: "Objects & Classes",
  design: "Deeper Object Design",
  memory: "Memory & the JVM",
  collections: "Collections & Generics",
  errors: "Exceptions & I/O",
  modern: "Modern Java",
  concurrency: "Concurrency",
  tooling: "Tooling & Practice",
  patterns: "Design Patterns",
}

interface LessonDefinition {
  slug: string
  order: number
  section: Section
  title: string
  shortTitle: string
  description: string
  icon: LucideIcon
  minutes: number
  /**
   * The raw dynamic import. Kept separate from `component` so it can also be
   * called on its own to warm the chunk before navigation — see prefetchLesson.
   */
  load: () => Promise<{ default: ComponentType }>
}

export interface Lesson extends LessonDefinition {
  component: ComponentType
}

const lessonDefinitions: LessonDefinition[] = [
  // ----------------------------------------------------------------- foundations
  {
    slug: "why-java",
    order: 1,
    section: "foundations",
    title: "Why Java Exists",
    shortTitle: "Why Java",
    description: "The problem Java was built to solve, and why it still runs most of the systems you rely on.",
    icon: Coffee,
    minutes: 6,
    load: () => import("@/lessons/01-why-java"),
  },
  {
    slug: "jdk-jre-jvm",
    order: 2,
    section: "foundations",
    title: "JDK, JRE & JVM",
    shortTitle: "JDK, JRE & JVM",
    description: "Three acronyms everyone confuses, separated once and for all with a diagram you can click through.",
    icon: Layers,
    minutes: 7,
    load: () => import("@/lessons/02-jdk-jre-jvm"),
  },
  {
    slug: "first-java-program",
    order: 3,
    section: "foundations",
    title: "Your First Java Program",
    shortTitle: "First Program",
    description: "Install a JDK, write Hello World, and understand every single word in it before moving on.",
    icon: Play,
    minutes: 9,
    load: () => import("@/lessons/03-first-java-program"),
  },
  {
    slug: "how-java-runs",
    order: 4,
    section: "foundations",
    title: "How Java Code Actually Runs",
    shortTitle: "How Java Runs",
    description: "Source to bytecode to machine code — the compile-and-JIT pipeline, step by step.",
    icon: Cpu,
    minutes: 9,
    load: () => import("@/lessons/04-how-java-runs"),
  },
  {
    slug: "anatomy-of-a-class",
    order: 5,
    section: "foundations",
    title: "Anatomy of a Java File",
    shortTitle: "Anatomy of a File",
    description: "Package, imports, class, fields, methods, main — what each line is for and where it must go.",
    icon: FileCode2,
    minutes: 8,
    load: () => import("@/lessons/05-anatomy-of-a-class"),
  },
  {
    slug: "variables-and-types",
    order: 6,
    section: "foundations",
    title: "Variables & Primitive Types",
    shortTitle: "Variables & Types",
    description: "The eight primitives, what each one costs, and why int overflows silently at 2,147,483,647.",
    icon: Variable,
    minutes: 10,
    load: () => import("@/lessons/06-variables-and-types"),
  },

  // ---------------------------------------------------------------------- syntax
  {
    slug: "operators",
    order: 7,
    section: "syntax",
    title: "Operators & Expressions",
    shortTitle: "Operators",
    description: "Arithmetic, comparison, logical and the ones that trip people up: %, ++, ternary, short-circuiting.",
    icon: Calculator,
    minutes: 9,
    load: () => import("@/lessons/07-operators"),
  },
  {
    slug: "control-flow",
    order: 8,
    section: "syntax",
    title: "if, else & switch",
    shortTitle: "if & switch",
    description: "Making decisions in code — including the switch fall-through bug everyone writes exactly once.",
    icon: Split,
    minutes: 9,
    load: () => import("@/lessons/08-control-flow"),
  },
  {
    slug: "loops",
    order: 9,
    section: "syntax",
    title: "Loops & Iteration",
    shortTitle: "Loops",
    description: "for, while, do-while, for-each — which to reach for, and how off-by-one errors happen.",
    icon: Repeat,
    minutes: 9,
    load: () => import("@/lessons/09-loops"),
  },
  {
    slug: "arrays",
    order: 10,
    section: "syntax",
    title: "Arrays",
    shortTitle: "Arrays",
    description: "Fixed-size, zero-indexed, and the source of your first ArrayIndexOutOfBoundsException.",
    icon: Grid2x2,
    minutes: 10,
    load: () => import("@/lessons/10-arrays"),
  },
  {
    slug: "strings",
    order: 11,
    section: "syntax",
    title: "Strings",
    shortTitle: "Strings",
    description: "The most-used class in Java: creating, comparing, slicing, formatting — and why == lies.",
    icon: Type,
    minutes: 11,
    load: () => import("@/lessons/11-strings"),
  },
  {
    slug: "methods",
    order: 12,
    section: "syntax",
    title: "Methods & Overloading",
    shortTitle: "Methods",
    description: "Parameters, return types, varargs, overloading, and how to name a method so it explains itself.",
    icon: SquareFunction,
    minutes: 10,
    load: () => import("@/lessons/12-methods"),
  },
  {
    slug: "casting-and-wrappers",
    order: 13,
    section: "syntax",
    title: "Casting, Wrappers & Autoboxing",
    shortTitle: "Casting & Wrappers",
    description: "Widening, narrowing, Integer vs int, and the caching quirk that makes 127 == 127 but 128 != 128.",
    icon: ArrowLeftRight,
    minutes: 10,
    load: () => import("@/lessons/13-casting-and-wrappers"),
  },

  // ------------------------------------------------------------------------- oop
  {
    slug: "classes-and-objects",
    order: 14,
    section: "oop",
    title: "Classes & Objects",
    shortTitle: "Classes & Objects",
    description: "The blueprint-and-instance idea, and what actually happens in memory when you type new.",
    icon: Box,
    minutes: 10,
    load: () => import("@/lessons/14-classes-and-objects"),
  },
  {
    slug: "constructors",
    order: 15,
    section: "oop",
    title: "Constructors & Initialization",
    shortTitle: "Constructors",
    description: "Default constructors, overloading, this(), and the exact order Java initialises an object in.",
    icon: Hammer,
    minutes: 11,
    load: () => import("@/lessons/15-constructors"),
  },
  {
    slug: "encapsulation",
    order: 16,
    section: "oop",
    title: "Encapsulation & Access Modifiers",
    shortTitle: "Encapsulation",
    description: "private, public, protected, package-private — and why getters aren't automatically encapsulation.",
    icon: Lock,
    minutes: 10,
    load: () => import("@/lessons/16-encapsulation"),
  },
  {
    slug: "static-members",
    order: 17,
    section: "oop",
    title: "static, final & Constants",
    shortTitle: "static & final",
    description: "What belongs to the class instead of the object, and why static state is so easy to abuse.",
    icon: Pin,
    minutes: 10,
    load: () => import("@/lessons/17-static-members"),
  },
  {
    slug: "inheritance",
    order: 18,
    section: "oop",
    title: "Inheritance & super",
    shortTitle: "Inheritance",
    description: "extends, constructor chaining, and the single-inheritance rule that shapes every Java hierarchy.",
    icon: Network,
    minutes: 11,
    load: () => import("@/lessons/18-inheritance"),
  },
  {
    slug: "polymorphism",
    order: 19,
    section: "oop",
    title: "Polymorphism & Overriding",
    shortTitle: "Polymorphism",
    description: "One reference, many behaviours — dynamic dispatch, @Override, and overloading vs overriding.",
    icon: Shapes,
    minutes: 11,
    load: () => import("@/lessons/19-polymorphism"),
  },
  {
    slug: "abstract-classes",
    order: 20,
    section: "oop",
    title: "Abstract Classes",
    shortTitle: "Abstract Classes",
    description: "Partial implementations: shared state and behaviour with the specifics left to subclasses.",
    icon: Frame,
    minutes: 9,
    load: () => import("@/lessons/20-abstract-classes"),
  },
  {
    slug: "interfaces",
    order: 21,
    section: "oop",
    title: "Interfaces",
    shortTitle: "Interfaces",
    description: "Contracts without implementation — plus default and static methods, and when to prefer one over an abstract class.",
    icon: Plug,
    minutes: 11,
    load: () => import("@/lessons/21-interfaces"),
  },
  {
    slug: "object-methods",
    order: 22,
    section: "oop",
    title: "equals, hashCode & toString",
    shortTitle: "equals & hashCode",
    description: "The three methods every class inherits, the contract between two of them, and what breaks when you ignore it.",
    icon: Equal,
    minutes: 12,
    load: () => import("@/lessons/22-object-methods"),
  },

  // ---------------------------------------------------------------------- design
  {
    slug: "composition-vs-inheritance",
    order: 23,
    section: "design",
    title: "Composition vs Inheritance",
    shortTitle: "Composition",
    description: "Why 'favour composition' is the most repeated advice in Java, with the fragile-base-class problem behind it.",
    icon: Puzzle,
    minutes: 10,
    load: () => import("@/lessons/23-composition-vs-inheritance"),
  },
  {
    slug: "enums",
    order: 24,
    section: "design",
    title: "Enums",
    shortTitle: "Enums",
    description: "Fixed sets of values done properly — with fields, methods, and per-constant behaviour.",
    icon: ToggleLeft,
    minutes: 10,
    load: () => import("@/lessons/24-enums"),
  },
  {
    slug: "records",
    order: 25,
    section: "design",
    title: "Records & Immutability",
    shortTitle: "Records",
    description: "Data carriers in one line, what the compiler generates for you, and when a record is the wrong choice.",
    icon: Receipt,
    minutes: 10,
    load: () => import("@/lessons/25-records"),
  },
  {
    slug: "nested-classes",
    order: 26,
    section: "design",
    title: "Nested, Inner & Anonymous Classes",
    shortTitle: "Nested Classes",
    description: "Four kinds of class-inside-a-class, the hidden outer reference, and where each one is actually used.",
    icon: PackageOpen,
    minutes: 10,
    load: () => import("@/lessons/26-nested-classes"),
  },
  {
    slug: "packages-and-access",
    order: 27,
    section: "design",
    title: "Packages, Imports & Structure",
    shortTitle: "Packages",
    description: "How Java finds your classes, the classpath, and how to lay out a project someone else can read.",
    icon: FolderTree,
    minutes: 9,
    load: () => import("@/lessons/27-packages-and-access"),
  },

  // ---------------------------------------------------------------------- memory
  {
    slug: "stack-and-heap",
    order: 28,
    section: "memory",
    title: "Stack, Heap & References",
    shortTitle: "Stack & Heap",
    description: "Where variables and objects actually live — the model that makes null and aliasing bugs obvious.",
    icon: MemoryStick,
    minutes: 12,
    load: () => import("@/lessons/28-stack-and-heap"),
  },
  {
    slug: "pass-by-value",
    order: 29,
    section: "memory",
    title: "Java Is Always Pass-by-Value",
    shortTitle: "Pass-by-Value",
    description: "The most misunderstood sentence in Java, settled with a diagram and two experiments.",
    icon: Send,
    minutes: 10,
    load: () => import("@/lessons/29-pass-by-value"),
  },
  {
    slug: "garbage-collection",
    order: 30,
    section: "memory",
    title: "Garbage Collection",
    shortTitle: "Garbage Collection",
    description: "How objects get freed, what reachability means, and why you still manage to leak memory in Java.",
    icon: Recycle,
    minutes: 11,
    load: () => import("@/lessons/30-garbage-collection"),
  },
  {
    slug: "string-pool-and-builders",
    order: 31,
    section: "memory",
    title: "The String Pool & StringBuilder",
    shortTitle: "String Pool",
    description: "Why strings are immutable, what the pool actually stores, and the loop that quietly allocates thousands of objects.",
    icon: Droplets,
    minutes: 11,
    load: () => import("@/lessons/31-string-pool-and-builders"),
  },

  // ----------------------------------------------------------------- collections
  {
    slug: "collections-overview",
    order: 32,
    section: "collections",
    title: "The Collections Framework",
    shortTitle: "Collections Map",
    description: "One diagram of the whole hierarchy, so you always know which interface you're actually programming to.",
    icon: Boxes,
    minutes: 10,
    load: () => import("@/lessons/32-collections-overview"),
  },
  {
    slug: "lists",
    order: 33,
    section: "collections",
    title: "Lists: ArrayList vs LinkedList",
    shortTitle: "Lists",
    description: "The two implementations, their real performance profiles, and why ArrayList wins more often than the Big-O table suggests.",
    icon: ListOrdered,
    minutes: 11,
    load: () => import("@/lessons/33-lists"),
  },
  {
    slug: "sets-and-maps",
    order: 34,
    section: "collections",
    title: "Sets & Maps",
    shortTitle: "Sets & Maps",
    description: "Uniqueness and key-value lookup — HashSet, TreeSet, LinkedHashMap, and picking between them.",
    icon: KeyRound,
    minutes: 12,
    load: () => import("@/lessons/34-sets-and-maps"),
  },
  {
    slug: "hashmap-internals",
    order: 35,
    section: "collections",
    title: "How HashMap Works",
    shortTitle: "HashMap Internals",
    description: "Buckets, collisions, treeification and resizing — the interview favourite, explained visually.",
    icon: Hash,
    minutes: 13,
    load: () => import("@/lessons/35-hashmap-internals"),
  },
  {
    slug: "sorting-and-comparators",
    order: 36,
    section: "collections",
    title: "Sorting, Comparable & Comparator",
    shortTitle: "Sorting",
    description: "Natural ordering vs custom ordering, comparator chaining, and the contract that keeps sorts stable.",
    icon: ArrowDownUp,
    minutes: 11,
    load: () => import("@/lessons/36-sorting-and-comparators"),
  },
  {
    slug: "generics",
    order: 37,
    section: "collections",
    title: "Generics",
    shortTitle: "Generics",
    description: "Type parameters that move errors from runtime to compile time — classes, methods and bounds.",
    icon: Braces,
    minutes: 12,
    load: () => import("@/lessons/37-generics"),
  },
  {
    slug: "wildcards-and-erasure",
    order: 38,
    section: "collections",
    title: "Wildcards & Type Erasure",
    shortTitle: "Wildcards",
    description: "? extends, ? super, PECS, and what generics actually compile down to.",
    icon: Asterisk,
    minutes: 12,
    load: () => import("@/lessons/38-wildcards-and-erasure"),
  },

  // ---------------------------------------------------------------------- errors
  {
    slug: "exceptions-basics",
    order: 39,
    section: "errors",
    title: "Exceptions: try, catch, finally",
    shortTitle: "Exceptions",
    description: "How an exception travels up the call stack, and how to read a stack trace from the bottom.",
    icon: TriangleAlert,
    minutes: 11,
    load: () => import("@/lessons/39-exceptions-basics"),
  },
  {
    slug: "checked-vs-unchecked",
    order: 40,
    section: "errors",
    title: "Checked vs Unchecked",
    shortTitle: "Checked vs Unchecked",
    description: "The split that divides Java developers — what the compiler forces, and when each kind is right.",
    icon: ShieldAlert,
    minutes: 10,
    load: () => import("@/lessons/40-checked-vs-unchecked"),
  },
  {
    slug: "custom-exceptions-and-resources",
    order: 41,
    section: "errors",
    title: "Custom Exceptions & try-with-resources",
    shortTitle: "Custom Exceptions",
    description: "Designing exceptions worth throwing, and letting the compiler close your files for you.",
    icon: LifeBuoy,
    minutes: 11,
    load: () => import("@/lessons/41-custom-exceptions-and-resources"),
  },
  {
    slug: "files-and-io",
    order: 42,
    section: "errors",
    title: "Files & I/O",
    shortTitle: "Files & I/O",
    description: "Reading and writing with modern java.nio.file, plus streams, readers and when buffering matters.",
    icon: HardDrive,
    minutes: 12,
    load: () => import("@/lessons/42-files-and-io"),
  },

  // ---------------------------------------------------------------------- modern
  {
    slug: "lambdas",
    order: 43,
    section: "modern",
    title: "Lambdas",
    shortTitle: "Lambdas",
    description: "Passing behaviour as an argument — the syntax, the capture rules, and method references.",
    icon: Zap,
    minutes: 11,
    load: () => import("@/lessons/43-lambdas"),
  },
  {
    slug: "functional-interfaces",
    order: 44,
    section: "modern",
    title: "Functional Interfaces",
    shortTitle: "Functional Interfaces",
    description: "Function, Predicate, Consumer, Supplier — the small vocabulary the whole Stream API is built on.",
    icon: Workflow,
    minutes: 10,
    load: () => import("@/lessons/44-functional-interfaces"),
  },
  {
    slug: "streams",
    order: 45,
    section: "modern",
    title: "Streams",
    shortTitle: "Streams",
    description: "Describe the result instead of the loop — sources, intermediate operations, and laziness.",
    icon: Waves,
    minutes: 13,
    load: () => import("@/lessons/45-streams"),
  },
  {
    slug: "collectors",
    order: 46,
    section: "modern",
    title: "Collectors & Grouping",
    shortTitle: "Collectors",
    description: "Turning a stream back into data: toList, joining, groupingBy, partitioningBy and friends.",
    icon: Filter,
    minutes: 12,
    load: () => import("@/lessons/46-collectors"),
  },
  {
    slug: "optional",
    order: 47,
    section: "modern",
    title: "Optional",
    shortTitle: "Optional",
    description: "A container for 'maybe nothing' — how to use it well, and the three ways people misuse it.",
    icon: CircleHelp,
    minutes: 10,
    load: () => import("@/lessons/47-optional"),
  },
  {
    slug: "modern-syntax",
    order: 48,
    section: "modern",
    title: "var, switch Expressions & Pattern Matching",
    shortTitle: "Modern Syntax",
    description: "The last decade of language changes that make everyday Java shorter: var, text blocks, sealed types.",
    icon: Sparkles,
    minutes: 12,
    load: () => import("@/lessons/48-modern-syntax"),
  },
  {
    slug: "date-and-time",
    order: 49,
    section: "modern",
    title: "Dates & Times",
    shortTitle: "Dates & Times",
    description: "java.time done right — LocalDate, Instant, ZonedDateTime, Duration, and why Date is retired.",
    icon: CalendarClock,
    minutes: 11,
    load: () => import("@/lessons/49-date-and-time"),
  },

  // ----------------------------------------------------------------- concurrency
  {
    slug: "threads",
    order: 50,
    section: "concurrency",
    title: "Threads",
    shortTitle: "Threads",
    description: "What a thread is, how to start one properly, and the lifecycle states you'll see in a thread dump.",
    icon: Activity,
    minutes: 12,
    load: () => import("@/lessons/50-threads"),
  },
  {
    slug: "synchronization",
    order: 51,
    section: "concurrency",
    title: "Race Conditions & synchronized",
    shortTitle: "Synchronization",
    description: "Why count++ loses updates, what a monitor lock does, and where volatile fits in.",
    icon: LockKeyhole,
    minutes: 13,
    load: () => import("@/lessons/51-synchronization"),
  },
  {
    slug: "executors-and-futures",
    order: 52,
    section: "concurrency",
    title: "Executors & CompletableFuture",
    shortTitle: "Executors",
    description: "Stop creating threads by hand — thread pools, Callable, Future, and composing async work.",
    icon: Gauge,
    minutes: 13,
    load: () => import("@/lessons/52-executors-and-futures"),
  },
  {
    slug: "concurrent-collections",
    order: 53,
    section: "concurrency",
    title: "Concurrent Collections & Virtual Threads",
    shortTitle: "Concurrent Java",
    description: "ConcurrentHashMap, atomics, and the Java 21 feature that changes how servers handle load.",
    icon: Rabbit,
    minutes: 12,
    load: () => import("@/lessons/53-concurrent-collections"),
  },

  // --------------------------------------------------------------------- tooling
  {
    slug: "build-tools",
    order: 54,
    section: "tooling",
    title: "Maven, Gradle & Dependencies",
    shortTitle: "Build Tools",
    description: "What a build tool does for you, how the dependency graph works, and reading a pom.xml.",
    icon: PackageCheck,
    minutes: 11,
    load: () => import("@/lessons/54-build-tools"),
  },
  {
    slug: "testing-with-junit",
    order: 55,
    section: "tooling",
    title: "Testing with JUnit",
    shortTitle: "Testing",
    description: "Writing tests that fail for the right reason — assertions, lifecycle, parameterised tests and mocks.",
    icon: FlaskConical,
    minutes: 12,
    load: () => import("@/lessons/55-testing-with-junit"),
  },
  {
    slug: "java-best-practices",
    order: 56,
    section: "tooling",
    title: "Best Practices & Common Pitfalls",
    shortTitle: "Best Practices",
    description: "The habits that separate readable Java from the kind you inherit and dread — plus a debugging cheat sheet.",
    icon: ClipboardCheck,
    minutes: 13,
    load: () => import("@/lessons/56-java-best-practices"),
  },

  // --------------------------------------------------------------------- patterns
  {
    slug: "design-patterns-overview",
    order: 57,
    section: "patterns",
    title: "What Design Patterns Are",
    shortTitle: "Patterns Overview",
    description: "Named solutions to recurring problems — the three categories, where the JDK uses them, and when not to reach for one.",
    icon: LibraryBig,
    minutes: 9,
    load: () => import("@/lessons/57-design-patterns-overview"),
  },
  {
    slug: "singleton-pattern",
    order: 58,
    section: "patterns",
    title: "Singleton",
    shortTitle: "Singleton",
    description: "One instance, shared everywhere — done safely with an enum, and the thread-safety traps of doing it by hand.",
    icon: CircleDot,
    minutes: 10,
    load: () => import("@/lessons/58-singleton-pattern"),
  },
  {
    slug: "factory-pattern",
    order: 59,
    section: "patterns",
    title: "Factory Method & Abstract Factory",
    shortTitle: "Factory",
    description: "Let a method decide which class to instantiate, so callers depend on an interface instead of a constructor.",
    icon: Factory,
    minutes: 11,
    load: () => import("@/lessons/59-factory-pattern"),
  },
  {
    slug: "builder-pattern",
    order: 60,
    section: "patterns",
    title: "Builder",
    shortTitle: "Builder",
    description: "Construct objects with many optional parts readably — and end the telescoping-constructor nightmare.",
    icon: Construction,
    minutes: 10,
    load: () => import("@/lessons/60-builder-pattern"),
  },
  {
    slug: "strategy-pattern",
    order: 61,
    section: "patterns",
    title: "Strategy",
    shortTitle: "Strategy",
    description: "Swap an algorithm at runtime by passing behaviour as an object — the pattern lambdas made trivial.",
    icon: Signpost,
    minutes: 10,
    load: () => import("@/lessons/61-strategy-pattern"),
  },
  {
    slug: "observer-pattern",
    order: 62,
    section: "patterns",
    title: "Observer",
    shortTitle: "Observer",
    description: "Notify many listeners when something changes, without the source knowing who they are — and the leak it invites.",
    icon: Radio,
    minutes: 11,
    load: () => import("@/lessons/62-observer-pattern"),
  },
  {
    slug: "decorator-pattern",
    order: 63,
    section: "patterns",
    title: "Decorator",
    shortTitle: "Decorator",
    description: "Add behaviour by wrapping, not subclassing — the pattern behind every java.io stream.",
    icon: Component,
    minutes: 11,
    load: () => import("@/lessons/63-decorator-pattern"),
  },
  {
    slug: "adapter-pattern",
    order: 64,
    section: "patterns",
    title: "Adapter",
    shortTitle: "Adapter",
    description: "Make two incompatible interfaces work together by wrapping one in the shape the other expects.",
    icon: Unplug,
    minutes: 9,
    load: () => import("@/lessons/64-adapter-pattern"),
  },
  {
    slug: "template-method-pattern",
    order: 65,
    section: "patterns",
    title: "Template Method",
    shortTitle: "Template Method",
    description: "Fix an algorithm's skeleton in a base class and let subclasses fill in the steps — safely.",
    icon: LayoutTemplate,
    minutes: 9,
    load: () => import("@/lessons/65-template-method-pattern"),
  },
  {
    slug: "proxy-pattern",
    order: 66,
    section: "patterns",
    title: "Proxy",
    shortTitle: "Proxy",
    description: "A stand-in that controls access to the real object — the mechanism behind Spring AOP and lazy loading.",
    icon: Radar,
    minutes: 11,
    load: () => import("@/lessons/66-proxy-pattern"),
  },
]

export const lessons: Lesson[] = lessonDefinitions.map((definition) => ({
  ...definition,
  component: lazy(definition.load),
}))

const prefetched = new Set<string>()

/**
 * Warms a lesson's chunk ahead of navigation, e.g. on link hover. The module
 * registry dedupes the import, so the lazy() component later resolves from the
 * already-fetched module instead of waiting on a fresh network round trip.
 */
export function prefetchLesson(slug: string) {
  if (prefetched.has(slug)) return
  const lesson = lessons.find((item) => item.slug === slug)
  if (!lesson) return
  prefetched.add(slug)
  // A failed prefetch is not worth surfacing — navigation will retry the import
  // and show the real error through Suspense.
  void lesson.load().catch(() => prefetched.delete(slug))
}

export function getLessonBySlug(slug: string | undefined) {
  return lessons.find((lesson) => lesson.slug === slug)
}

export function getAdjacentLessons(slug: string) {
  const index = lessons.findIndex((lesson) => lesson.slug === slug)
  return {
    previous: index > 0 ? lessons[index - 1] : undefined,
    next: index >= 0 && index < lessons.length - 1 ? lessons[index + 1] : undefined,
  }
}

export function getLessonsBySection() {
  return (Object.keys(SECTIONS) as Section[]).map((section) => ({
    section,
    label: SECTIONS[section],
    lessons: lessons.filter((lesson) => lesson.section === section),
  }))
}
